var v=new Set(["tagName","element","children"]);function x(b,f=null){if(Array.isArray(b))for(let d=0;d<b.length;d++)y(b[d],f,d);else y(b,f)}function z(b,f){function d(){return e}function l(h){if(h==e)return e;e=h;x(b,null);return e}var e=b[f];return{set:v.has(f)?d:l,get:function(){return e}}}
function y(b,f,d=null){if(b!=null){b.children==null&&(b.children=[]);if(!b.element){b.element=document.createElement(b.tagName);for(var l in b)Object.defineProperty(b,l,z(b,l));f&&A(b.element,f,d)}f&&b.element.parentElement!=f?A(b.element,f,d):f&&d!=null&&f.children[d]!=b.element&&A(b.element,f,d);b.children==null&&(b.children=[]);f={};for(var e in b)if(!v.has(e))if(e=="text")if(d=b.element,l=b.text,d.childNodes.length>0)for(let m=0;m<d.childNodes.length;m++){if(d.childNodes[m].nodeType==3){d.childNodes[m].textContent!=
l&&(d.childNodes[m].textContent=l);break}}else d.innerText!=l&&(d.innerText=l);else e=="class"?b.element.className!=b["class"]&&(b.element.className=b["class"]):e.startsWith("on-")?f[e.substring(3)]=b[e]:b.element[e]!=b[e]&&(b.element[e]=b[e]);e=b.element;d=e.h;d||(e.h=d={});for(var h in d)h in f&&d[h]==f[h]||h in f&&d[h]==f[h]||(e.removeEventListener(h,d[h]),delete d[h]);for(let m in f)m in d||(e.addEventListener(m,f[m]),d[m]=f[m]);h=b.element.g;var n;h||(b.element.g=h=[]);if("children"in b)for(var q in b.children)y(b.children[q],
b.element,q),h.indexOf(b.children[q])==-1&&h.push(b.children[q]);for(q=h.length-1;q>=0;q--)b.children.indexOf(h[q])==-1&&(n=h.splice(q,1)[0])&&n.element.remove()}}function A(b,f,d=null){d==null||d>=f.children.length?f.appendChild(b):f.insertBefore(b,f.children[d])}function B(b,f,d,l,e){b={tagName:b,"class":f,text:d,children:e};for(let h in l)b[h]=l[h];return b}var E=(b,f=null,d=[])=>B("div",b,f,null,d),F=(b,f=null,d=null)=>B("button",b,f,d,[]);
function G(b,f,d,l=[]){var e={tagName:"input","class":b,type:f,children:l};for(let n in d)e[n]=d[n];var h=e["on-change"];e["on-change"]=n=>{e.value=n.target.value;e.checked!=void 0&&(e.checked=n.target.checked);h&&h(n)};return e}function H(b,f,d,l){b={tagName:"label","class":b,text:f,children:l};for(let e in d)b[e]=d[e];return b}
function I(){async function b(a){a=new Uint8Array(a);return await fetch("/",{method:"POST",headers:{"Content-Type":"application/octet-stream"},body:a})}function f(a){if(a&&a.byteLength){var c=new DataView(a);a=a.byteLength/32;for(let g=0;g<a;g++)d(c,g*32)}}function d(a,c){let g=E("h","",[n(a.getUint8(c+0),a.getUint8(c+1),a.getUint8(c+2)),n(a.getUint8(c+3),a.getUint8(c+4),a.getUint8(c+5)),n(a.getUint8(c+6),a.getUint8(c+7),a.getUint8(c+8)),n(a.getUint8(c+9),a.getUint8(c+10),a.getUint8(c+11)),n(a.getUint8(c+
12),a.getUint8(c+13),a.getUint8(c+14)),n(a.getUint8(c+15),a.getUint8(c+16),a.getUint8(c+17)),h("Position Offset",C,a.getUint16(c+18,!0)),h("Position Skip",J,a.getInt8(c+20)),h("Position Delay",u,a.getUint8(c+21)),h("Color Offset",u,a.getUint8(c+22)),h("Color Skip",u,a.getUint8(c+23)),h("Color Delay",u,a.getUint8(c+24)),h("Repeat",u,a.getUint8(c+25)),h("Range Length",C,a.getUint16(c+26,!0)),h("Range Offset",C,a.getUint16(c+28,!0)),...l(a.getUint8(c+30)),F("r","remove",{"on-click":function(){let k=
t.indexOf(g);k!=-1&&t.splice(k,1);x(D,null);q()}})]);t.push(g);x(D,null)}function l(a){console.log(a&1);return[e("Clear Previous",a&1),e("Random Position",a&2),e("Random Color",a&4),e("Delayed Update",a&8),e("Sinusoidal",a&16),e("",a&32),e("",a&64),e("",a&128)]}function e(a,c){return H("l",a,"",[G("x","checkbox",{"on-change":q,checked:!!c})])}function h(a,c,g){c=[...c];c[2].value=g.toString();c[2]["on-change"]=q;return H("n",a,null,[G(...c)])}function n(a,c,g){var k=[...K];k[2].value="#"+a.toString(16).padStart(2,
"0")+c.toString(16).padStart(2,"0")+g.toString(16).padStart(2,"0");k[2]["on-change"]=q;return H("c",null,null,[G(...k)])}function q(){console.log("sending");var a=new ArrayBuffer(t.length*32),c=new DataView(a);for(let w=0;w<t.length;w++){var g=t[w].children,k=c,p=w*32;m(g[0],k,p+0);m(g[1],k,p+3);m(g[2],k,p+6);m(g[3],k,p+9);m(g[4],k,p+12);m(g[5],k,p+15);k.setUint16(p+18,r(g[6]),!0);k.setInt8(p+20,r(g[7]));k.setUint8(p+21,r(g[8]));k.setUint8(p+22,r(g[9]));k.setUint8(p+23,r(g[10]));k.setUint8(p+24,r(g[11]));
k.setUint8(p+25,r(g[12]));k.setUint16(p+26,r(g[13]),!0);k.setUint16(p+28,r(g[14]),!0);k.setUint8(p+30,g[15].children[0].checked*1+g[16].children[0].checked*2+g[17].children[0].checked*4+g[18].children[0].checked*8+g[19].children[0].checked*16+g[20].children[0].checked*32+g[21].children[0].checked*64+g[22].children[0].checked*128)}b(a)}function m(a,c,g){a=r(a);c.setUint8(g+0,parseInt(a.slice(1,3),16));c.setUint8(g+1,parseInt(a.slice(3,5),16));c.setUint8(g+2,parseInt(a.slice(5,7),16))}function r(a){return a.children.length?
a.children[0].value:null}const C=["v","number",{min:"0",max:"65535",value:"0"}],u=["v","number",{min:"0",max:"255",value:"0"}],J=["v","number",{min:"-128",max:"127",value:"0"}],K=["v","color",{value:"#000000"}];let t,D=E("",null,t=[]),L=E("",null,[D,F("a","add",{"on-click":function(){f(new ArrayBuffer(32));q()}})]);x(L,document.body);(async function(){var a=await fetch("/bin");if(!a.ok)return null;a=await a.arrayBuffer();var c;a.byteLength===0?c=[]:a instanceof ArrayBuffer?c=a:a instanceof Uint8Array&&
(c=a.buffer.slice(a.byteOffset,a.byteOffset+a.byteLength));return c})().then(f)}window.addEventListener("load",()=>new I);
